settings:
  timeout: 30000 # Request timeout in ms
  retries: 3 # Retry failed fetches
  large_content_threshold: 1048576 # 1MB warning threshold
  error_notification_threshold: 3 # Only notify after this many consecutive errors
  error_notification_cooldown_ms: 3600000 # 1 hour cooldown between error notifications

websites:
  - name: OLG Düsseldorf Prüfungsamt
    url: https://www.olg-duesseldorf.nrw.de/aufgaben/pruefungsamt/06aktuelles/index.php
    selector: 'a[href$=".pdf"]' # Only monitor PDF links to catch new result lists
    enabled: true
    priority: high
    notifiers:
      - type: webhook
        url: https://examensradar.de/api/webhook/results
        method: POST
        headers:
          Content-Type: application/json
          Authorization: Bearer ${EXAMENSRADAR_WEBHOOK_SECRET}
        body: |
          {"jpa_slug": "düsseldorf"}

  # Example: Website with custom inline webhook notifier
  # - name: Critical Service
  #   url: https://critical.example.com
  #   enabled: true
  #   priority: urgent
  #   notifiers:
  #     - type: webhook
  #       url: ${CUSTOM_WEBHOOK_URL}
  #       method: POST
  #       headers:
  #         Content-Type: application/json
  #         Authorization: Bearer ${AUTH_TOKEN}
  #       body: |
  #         {
  #           "service": "{{name}}",
  #           "alert": "{{title}}",
  #           "details": "{{message}}",
  #           "link": "{{url}}"
  #         }

  # Example: Website with multiple notifiers (named + inline)
  # - name: Important Page
  #   url: https://important.example.com
  #   enabled: true
  #   priority: high
  #   notifiers:
  #     - slack              # Reference named channel
  #     - type: ntfy         # Inline ntfy with different topic
  #       topic: important-alerts
  #       server: https://ntfy.sh

# Template variables available in webhook body:
# {{title}}       - Notification title
# {{message}}     - Full notification message
# {{url}}         - Website URL being monitored
# {{name}}        - Website name
# {{priority}}    - Priority level (urgent, high, default, low, min)
# {{priority_num}} - Priority as number (5, 4, 3, 2, 1)
# {{tags}}        - Comma-separated tags
# {{timestamp}}   - ISO timestamp
# {{event}}       - Event type (change, error, initial)
# {{hash}}        - Content hash (for changes)
# {{diff}}        - Diff content (if available)
